name: CI Tests for PR
on:
  pull_request:
    branches:
      - master
jobs:
  validate-commits:
    name: Validate Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git fetch origin master
      - uses: flux-framework/pr-validator@master

  format-and-lint:
    name: Check Formatting and Run Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt -- --check

  run-ci-tests:
    name: Run CI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [focal, centos8]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Cache ~/.cargo contents
        id: cache-cargo
        uses: actions/cache@v2
        with:
          key: ${{ matrix.image }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target
      -
        name: run CI script
        run: src/test/docker-run-checks.sh --image=${{ matrix.image }}
